-- Single Unit Graphics - Alternate Settlers
------------------------------------------------

UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 
	WHERE Type IN (SELECT UnitMemberInfoType FROM ArtDefine_UnitInfoMemberInfos 
	WHERE UnitInfoType LIKE 'ART_DEF_UNIT__SETTLER%');
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AFRIMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AFRIFEMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AMERMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_AMERFEMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_EUROMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_EUROFEMALE%';
UPDATE ArtDefine_UnitMemberInfos SET Scale = 0.25 WHERE Type LIKE 'ART_DEF_UNIT_MEMBER_SETTLER%';

--Africa:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AFRI';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AFRI','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SONGHAI'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SONGHAI','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ETHIOPIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ETHIOPIA','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ZULU'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ZULU','ART_DEF_UNIT_MEMBER_AFRIMALE1',"1");

--Americas:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AMER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMER','ART_DEF_UNIT_MEMBER_AMERMALE2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AZTEC'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AZTEC','ART_DEF_UNIT_MEMBER_AMERMALE1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MAYA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MAYA','ART_DEF_UNIT_MEMBER_AMERMALE1',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SHOSHONE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SHOSHONE','ART_DEF_UNIT_MEMBER_AMERMALE2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_IROQUOIS'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_IROQUOIS','ART_DEF_UNIT_MEMBER_AMERMALE4',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INCA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INCA','ART_DEF_UNIT_MEMBER_AMERMALE4',"1");

--Asia:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ASIA';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INDIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_INDOESIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_INDONESIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_POLYNESIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLYNESIA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M1',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MONGOL'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MONGOL','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_HUNS'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_HUNS','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_JAPAN'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_JAPAN','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M3',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_KOREA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_KOREA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M3',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CHINA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CHINA','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M4',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SIAM'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SIAM','ART_DEF_UNIT_MEMBER_SETTLERS_ASIAN_M4',"1");

--Europe:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_EURO';
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EURO','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AMERICA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AMERICA','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ENGLAND'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ENGLAND','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_DENMARK'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_DENMARK','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_AUSTRIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_AUSTRIA','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_NETHERLANDS'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_NETHERLANDS','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CELTS'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CELTS','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SWEDEN'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SWEDEN','ART_DEF_UNIT_MEMBER_EUROMALE20',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BRAZIL'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BRAZIL','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_PORTUGAL'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PORTUGAL','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_SPAIN'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_SPAIN','ART_DEF_UNIT_MEMBER_EUROMALE25',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_FRANCE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_FRANCE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_GERMANY'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GERMANY','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_POLAND'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_POLAND','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_RUSSIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_RUSSIA','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");

--Mediterranean:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MED'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MED','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BYZANTIUM'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BYZANTIUM','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_GREECE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_GREECE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ROME'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ROME','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_VENICE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_VENICE','ART_DEF_UNIT_MEMBER_EUROMALE35',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_BABYLON'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_BABYLON','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_CARTHAGE'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_CARTHAGE','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");

--Middle East:
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MIDEAST'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MIDEAST','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");

DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ARABIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ARABIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_ASSYRIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_ASSYRIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_EGYPT'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_EGYPT','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_MOROCCO'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_MOROCCO','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_OTTOMAN'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_OTTOMAN','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
DELETE FROM ArtDefine_UnitInfoMemberInfos WHERE UnitInfoType='ART_DEF_UNIT__SETTLER_PERSIA'; --R.E.D.
INSERT INTO ArtDefine_UnitInfoMemberInfos VALUES ('ART_DEF_UNIT__SETTLER_PERSIA','ART_DEF_UNIT_MEMBER_AFRIMALE2',"1");
