-- --==========================================================================================================================	
-- -- Audio_Sounds
-- --==========================================================================================================================		
-- INSERT INTO Audio_Sounds 
-- 			(SoundID, 									Filename, 		LoadType)
-- VALUES		('SND_DOM_SPEECH_PHILIPPINES', 				'DOMRizal', 	'DynamicResident'),
-- 			('SND_LEADER_MUSIC_JFD_RIZAL_PEACE', 		'RizalPeace', 	'DynamicResident'),
-- 			('SND_LEADER_MUSIC_JFD_RIZAL_WAR', 			'RizalWar', 	'DynamicResident');			
-- --==========================================================================================================================	
-- -- Audio_2DSounds
-- --==========================================================================================================================		
-- INSERT INTO Audio_2DSounds 
-- 			(ScriptID, 									SoundID, 								SoundType, 		MinVolume, 	MaxVolume,	IsMusic,	Looping)
-- VALUES		('AS2D_DOM_SPEECH_PHILIPPINES', 			'SND_DOM_SPEECH_PHILIPPINES', 			'GAME_SPEECH', 	100, 		100, 		0, 			0),
-- 			('AS2D_LEADER_MUSIC_JFD_RIZAL_PEACE', 		'SND_LEADER_MUSIC_JFD_RIZAL_PEACE', 	'GAME_MUSIC', 	120, 		120, 		1, 			0),
-- 			('AS2D_LEADER_MUSIC_JFD_RIZAL_WAR', 		'SND_LEADER_MUSIC_JFD_RIZAL_WAR', 		'GAME_MUSIC', 	120, 		120, 		1,			0);
-- --==========================================================================================================================		
-- --==========================================================================================================================		
