/*-**************-*\
Colonialist Legacies' Australia
Buildings
Civitar
\*-**************-*/

INSERT INTO BuildingClasses (Type,											DefaultBuilding,							NoLimit) VALUES
							('BUILDINGCLASS_CL_AUSTRALIA_PUPPET_TOURISM',	'BUILDING_CL_AUSTRALIA_PUPPET_TOURISM',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_16',	'BUILDING_CL_AUSTRALIA_TRADE_TOURISM_16',	1),
							('BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_8',	'BUILDING_CL_AUSTRALIA_TRADE_TOURISM_8',	1),
							('BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_4',	'BUILDING_CL_AUSTRALIA_TRADE_TOURISM_4',	1),
							('BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_2',	'BUILDING_CL_AUSTRALIA_TRADE_TOURISM_2',	1),
							('BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_1',	'BUILDING_CL_AUSTRALIA_TRADE_TOURISM_1',	1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_64',	'BUILDING_CL_AUSTRALIA_PM_TOURISM_64',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_32',	'BUILDING_CL_AUSTRALIA_PM_TOURISM_32',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_16',	'BUILDING_CL_AUSTRALIA_PM_TOURISM_16',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_8',		'BUILDING_CL_AUSTRALIA_PM_TOURISM_8',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_4',		'BUILDING_CL_AUSTRALIA_PM_TOURISM_4',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_2',		'BUILDING_CL_AUSTRALIA_PM_TOURISM_2',		1),
							('BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_1',		'BUILDING_CL_AUSTRALIA_PM_TOURISM_1',		1);
INSERT INTO Buildings (Type,										BuildingClass,									Cost,	GreatWorkCount,	TechEnhancedTourism,	EnhancedYieldTech,	NeverCapture,	ShowInPedia) VALUES
					  ('BUILDING_CL_AUSTRALIA_PUPPET_TOURISM',		'BUILDINGCLASS_CL_AUSTRALIA_PUPPET_TOURISM',	-1,		-1,				1,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_TRADE_TOURISM_16',	'BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_16',	-1,		-1,				16,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_TRADE_TOURISM_8',		'BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_8',	-1,		-1,				8,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_TRADE_TOURISM_4',		'BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_4',	-1,		-1,				4,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_TRADE_TOURISM_2',		'BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_2',	-1,		-1,				2,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_TRADE_TOURISM_1',		'BUILDINGCLASS_CL_AUSTRALIA_TRADE_TOURISM_1',	-1,		-1,				1,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_64',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_64',		-1,		-1,				64,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_32',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_32',		-1,		-1,				32,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_16',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_16',		-1,		-1,				16,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_8',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_8',		-1,		-1,				8,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_4',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_4',		-1,		-1,				4,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_2',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_2',		-1,		-1,				2,						'TECH_AGRICULTURE',	1,				0),
					  ('BUILDING_CL_AUSTRALIA_PM_TOURISM_1',		'BUILDINGCLASS_CL_AUSTRALIA_PM_TOURISM_1',		-1,		-1,				1,						'TECH_AGRICULTURE',	1,				0);