/*-**************-*\
Colonialist Legacies' Australia
Leader
Civitar
\*-**************-*/

INSERT INTO Leaders (Type,						Description,						Civilopedia,							ArtDefineTag,				IconAtlas,				PortraitIndex,	VictoryCompetitiveness,	WonderCompetitiveness,	MinorCivCompetitiveness,	Boldness,	DiploBalance,	WarmongerHate,	DenounceWillingness,	DoFWillingness,	Loyalty,	Neediness,	Forgiveness,	Chattiness,	Meanness) VALUES
					('LEADER_CL_HENRY_PARKES',	'TXT_KEY_LEADER_CL_HENRY_PARKES',	'TXT_KEY_LEADER_CL_HENRY_PARKES_PEDIA',	'henry_parkes_scene.xml',	'CL_AUSTRALIA_ATLAS',	1,				6,						5,						6,							6,			6,				6,				6,						4,				7,			6,			6,				7,			3);
INSERT INTO Leader_MajorCivApproachBiases (LeaderType,					MajorCivApproachType,			Bias) VALUES
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_WAR',		3),
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_HOSTILE',	3),
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_DECEPTIVE',	3),
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_GUARDED',	4),
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_AFRAID',	2),
										  ('LEADER_CL_HENRY_PARKES',	'MAJOR_CIV_APPROACH_FRIENDLY',	8);
INSERT INTO Leader_MinorCivApproachBiases (LeaderType,					MinorCivApproachType,				Bias) VALUES
										  ('LEADER_CL_HENRY_PARKES',	'MINOR_CIV_APPROACH_IGNORE',		4),
										  ('LEADER_CL_HENRY_PARKES',	'MINOR_CIV_APPROACH_FRIENDLY',		7),
										  ('LEADER_CL_HENRY_PARKES',	'MINOR_CIV_APPROACH_PROTECTIVE',	4),
										  ('LEADER_CL_HENRY_PARKES',	'MINOR_CIV_APPROACH_CONQUEST',		3),
										  ('LEADER_CL_HENRY_PARKES',	'MINOR_CIV_APPROACH_BULLY',			3);
INSERT INTO Leader_Flavors (LeaderType,					FlavorType,							Flavor) VALUES
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_OFFENSE',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_DEFENSE',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_CITY_DEFENSE',				6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_MILITARY_TRAINING',			8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_RECON',						4),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_RANGED',					5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_MOBILE',					5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_NAVAL',						8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_NAVAL_RECON',				6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_NAVAL_GROWTH',				7),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_NAVAL_TILE_IMPROVEMENT',	8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_AIR',						6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_EXPANSION',					8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_GROWTH',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_TILE_IMPROVEMENT',			7),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_INFRASTRUCTURE',			9),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_PRODUCTION',				8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_GOLD',						4),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_SCIENCE',					7),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_CULTURE',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_HAPPINESS',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_GREAT_PEOPLE',				7),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_WONDER',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_RELIGION',					3),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_DIPLOMACY',					8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_SPACESHIP',					5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_WATER_CONNECTION',			9),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_NUKE',						5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_USE_NUKE',					5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_ESPIONAGE',					5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_ANTIAIR',					6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_AIR_CARRIER',				6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_ARCHAEOLOGY',				5),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_I_LAND_TRADE_ROUTE',		2),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_I_SEA_TRADE_ROUTE',			8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_I_TRADE_ORIGIN',			6),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_I_TRADE_DESTINATION',		8),
						   ('LEADER_CL_HENRY_PARKES',	'FLAVOR_AIRLIFT',					5);
INSERT INTO Leader_Traits (LeaderType,					TraitType) VALUES
						  ('LEADER_CL_HENRY_PARKES',	'TRAIT_CL_BOUNDLESS_PLAINS_TO_SHARE');
INSERT INTO Diplomacy_Responses (LeaderType,				ResponseType,									Response) VALUES
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_FIRST_GREETING',						'TXT_KEY_LEADER_CL_HENRY_PARKES_FIRST_GREETING%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_GREETING_POLITE_HELLO',				'TXT_KEY_LEADER_CL_HENRY_PARKES_POLITE_HELLO%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_GREETING_NEUTRAL_HELLO',				'TXT_KEY_LEADER_CL_HENRY_PARKES_NEUTRAL_HELLO%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_GREETING_HOSTILE_HELLO',				'TXT_KEY_LEADER_CL_HENRY_PARKES_HOSTILE_HELLO%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_DEFEATED',							'TXT_KEY_LEADER_CL_HENRY_PARKES_DEFEATED%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_REQUEST',								'TXT_KEY_LEADER_CL_HENRY_PARKES_REQUEST%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_LUXURY_TRADE',						'TXT_KEY_LEADER_CL_HENRY_PARKES_LUXURY_TRADE%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_OPEN_BORDERS_EXCHANGE',				'TXT_KEY_LEADER_CL_HENRY_PARKES_OPEN_BORDERS%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',	'TXT_KEY_LEADER_CL_HENRY_PARKES_HOSTILE_AGGRESSIVE_MILITARY_WARNING%'),
								('LEADER_CL_HENRY_PARKES',	'RESPONSE_EXPANSION_SERIOUS_WARNING',			'TXT_KEY_LEADER_CL_HENRY_PARKES_EXPANSION_SERIOUS_WARNING%');