/*-**************-*\
Colonialist Legacies' Australia
Civilization
Civitar
\*-**************-*/

INSERT INTO Civilizations (Type,						Description,							ShortDescription,							Adjective,									DefaultPlayerColor,			CivilopediaTag,								DawnOfManQuote,								ArtDefineTag,					ArtStyleType,			ArtStylePrefix,	ArtStyleSuffix,	IconAtlas,				AlphaIconAtlas,				PortraitIndex,	MapImage,				DawnOfManQuote,								DawnOfManImage,			DawnOfManAudio,		SoundtrackTag) VALUES
						  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA_SHORT',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA_ADJ',	'PLAYERCOLOR_CL_AUSTRALIA',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA_PEDIA',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA_DOM',	'ART_DEF_CIVILIZATION_ENGLAND',	'ARTSTYLE_EUROPEAN',	'EUROPEAN',		'_EURO',		'CL_AUSTRALIA_ATLAS',	'CL_AUSTRALIA_ALPHA_ATLAS',	0,				'CL_AustraliaMap.dds',	'TXT_KEY_CIVILIZATION_CL_AUSTRALIA_DOM',	'CL_AustraliaDOM.dds',	'AS2D_DOM_SPEECH_CL_AUSTRALIA',	'ENGLAND');
INSERT INTO Civilization_Leaders (CivilizationType,				LeaderheadType) VALUES
								 ('CIVILIZATION_CL_AUSTRALIA',	'LEADER_CL_HENRY_PARKES');
INSERT INTO Civilization_UnitClassOverrides (CivilizationType,				UnitClassType,					UnitType) VALUES
											('CIVILIZATION_CL_AUSTRALIA',	'UNITCLASS_GREAT_WAR_INFANTRY',	'UNIT_CL_AUSTRALIA_DIGGER'),
											('CIVILIZATION_CL_AUSTRALIA',	'UNITCLASS_WRITER',				'UNIT_CL_AUSTRALIA_PRIME_MINISTER'),
											('CIVILIZATION_CL_AUSTRALIA',	'UNITCLASS_WORKER',				'UNIT_CL_AUSTRALIA_WORKER');
INSERT INTO Civilization_FreeBuildingClasses (CivilizationType,				BuildingClassType) VALUES
											 ('CIVILIZATION_CL_AUSTRALIA',	'BUILDINGCLASS_PALACE');
INSERT INTO Civilization_FreeTechs (CivilizationType,				TechType) VALUES
								   ('CIVILIZATION_CL_AUSTRALIA',	'TECH_AGRICULTURE');
INSERT INTO Civilization_FreeUnits (CivilizationType,				UnitClassType,			UnitAIType,			Count) VALUES
								   ('CIVILIZATION_CL_AUSTRALIA',	'UNITCLASS_SETTLER',	'UNITAI_SETTLE',	1);
INSERT INTO Civilization_Religions (CivilizationType,				ReligionType) VALUES
								   ('CIVILIZATION_CL_AUSTRALIA',	'RELIGION_CHRISTIANITY');
INSERT INTO Civilization_SpyNames (CivilizationType,			SpyName) VALUES
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_0'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_1'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_2'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_3'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_4'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_5'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_6'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_7'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_8'),
								  ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_SPY_NAME_CL_AUSTRALIA_9');
INSERT INTO Civilization_CityNames (CivilizationType,				CityName) VALUES
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_SYDNEY'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_MELBOURNE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BRISBANE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_CANBERRA'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_PERTH'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_ADELAIDE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_GOLD_COAST'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_DARWIN'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_HOBART'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_GREATER_NEWCASTLE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_SUNSHINE_COAST'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_WOLLONGONG'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_GEELONG'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_TOWNSVILLE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_CAIRNS'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_MILDURA'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_TOOWOOMBA'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BALLARAT'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BENDIGO'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_LAUNCESTON'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_ALBURY'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_MACKAY'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_ROCKHAMPTON'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BUNDABURG'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BUNBURY'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_COFFS_HARBOUR'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_HERVEY_BAY'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_BROKEN_HILL'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_SHEPPARTON'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_GLADSTONE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_PORT_MACQUARIE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_TAMWORTH'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_TRALAGON'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_ORANGE'),
								   ('CIVILIZATION_CL_AUSTRALIA',	'TXT_KEY_CITY_NAME_CL_AUSTRALIA_GERALDTON');
INSERT INTO Civilization_Start_Along_Ocean (CivilizationType,				StartAlongOcean) VALUES
										   ('CIVILIZATION_CL_AUSTRALIA',	1);