/*-**************-*\
Colonialist Legacies' Australia
Promotions
Civitar
\*-**************-*/

INSERT INTO UnitPromotions (Type,												Description,												Help,															PediaEntry,													PediaType,			Sound,				IconAtlas,			PortraitIndex) VALUES
						   ('PROMOTION_CL_AUSTRALIA_DIGGER_FOREIGN_BONUS',		'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_FOREIGN_BONUS',		'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_FOREIGN_BONUS_HELP',		'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_FOREIGN_BONUS',		'PEDIA_ATTRIBUTES',	'AS2D_IF_LEVELUP',	'ABILITY_ATLAS',	59),
						   ('PROMOTION_CL_AUSTRALIA_DIGGER_COAST_BONUS_DUMMY',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_COAST_BONUS_DUMMY',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_COAST_BONUS_DUMMY_HELP',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_DIGGER_COAST_BONUS_DUMMY',	'PEDIA_ATTRIBUTES',	'AS2D_IF_LEVELUP',	'ABILITY_ATLAS',	59),
						   ('PROMOTION_CL_AUSTRALIA_PRIME_MINISTER_TOURISM',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_PRIME_MINISTER_TOURISM',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_PRIME_MINISTER_TOURISM_HELP',	'TXT_KEY_PROMOTION_CL_AUSTRALIA_PRIME_MINISTER_TOURISM',	'PEDIA_ATTRIBUTES',	'AS2D_IF_LEVELUP',	'ABILITY_ATLAS',	59),
						   ('PROMOTION_CL_AUSTRALIA_WORKER_UPGRADE',			'TXT_KEY_PROMOTION_CL_AUSTRALIA_WORKER_UPGRADE',			'TXT_KEY_PROMOTION_CL_AUSTRALIA_WORKER_UPGRADE_HELP',			'TXT_KEY_PROMOTION_CL_AUSTRALIA_WORKER_UPGRADE',			'PEDIA_ATTRIBUTES',	'AS2D_IF_LEVELUP',	'ABILITY_ATLAS',	59);
UPDATE UnitPromotions SET OutsideFriendlyLandsModifier = 15 WHERE Type = 'PROMOTION_CL_AUSTRALIA_DIGGER_FOREIGN_BONUS';
--hidden promotion
INSERT INTO UnitPromotions (Type,											ShowInPedia,	ShowInUnitPanel,	CombatPercent) VALUES
						   ('PROMOTION_CL_AUSTRALIA_DIGGER_COAST_BONUS',	0,				0,					15);