/*-**************-*\
Colonialist Legacies' Australia
Great Works
Civitar
\*-**************-*/

INSERT INTO GreatWorks (Type,										Description,										Quote,														GreatWorkClassType,			Image,							Audio) VALUES
					   ('GREAT_WORK_CL_BROADCAST_OPENING',			'TXT_KEY_GREAT_WORK_CL_BROADCAST_OPENING',			'TXT_KEY_GREAT_WORK_CL_BROADCAST_OPENING_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_ELDERS',						'TXT_KEY_GREAT_WORK_CL_ELDERS',						'TXT_KEY_GREAT_WORK_CL_ELDERS_QUOTE',						'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_ON_PROGRESS',				'TXT_KEY_GREAT_WORK_CL_ON_PROGRESS',				'TXT_KEY_GREAT_WORK_CL_ON_PROGRESS_QUOTE',					'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_PARLIAMENTARY_DEBATE',		'TXT_KEY_GREAT_WORK_CL_PARLIAMENTARY_DEBATE',		'TXT_KEY_GREAT_WORK_CL_PARLIAMENTARY_DEBATE_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_APOLOGY_TO_ABORIGINALS',		'TXT_KEY_GREAT_WORK_CL_APOLOGY_TO_ABORIGINALS',		'TXT_KEY_GREAT_WORK_CL_APOLOGY_TO_ABORIGINALS_QUOTE',		'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_SPEECH_TO_THE_HOUSE',		'TXT_KEY_GREAT_WORK_CL_SPEECH_TO_THE_HOUSE',		'TXT_KEY_GREAT_WORK_CL_SPEECH_TO_THE_HOUSE_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_JANUARY_1_1901',				'TXT_KEY_GREAT_WORK_CL_JANUARY_1_1901',				'TXT_KEY_GREAT_WORK_CL_JANUARY_1_1901_QUOTE',				'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_ON_ENLISTMENT',				'TXT_KEY_GREAT_WORK_CL_ON_ENLISTMENT',				'TXT_KEY_GREAT_WORK_CL_ON_ENLISTMENT_QUOTE',				'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_LIGHT_ON_THE_HILL',			'TXT_KEY_GREAT_WORK_CL_LIGHT_ON_THE_HILL',			'TXT_KEY_GREAT_WORK_CL_LIGHT_ON_THE_HILL_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_ABC_RADIO',					'TXT_KEY_GREAT_WORK_CL_ABC_RADIO',					'TXT_KEY_GREAT_WORK_CL_ABC_RADIO_QUOTE',					'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_UPON_BEING_SACKED',			'TXT_KEY_GREAT_WORK_CL_UPON_BEING_SACKED',			'TXT_KEY_GREAT_WORK_CL_UPON_BEING_SACKED_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_ABC_LATELINE',				'TXT_KEY_GREAT_WORK_CL_ABC_LATELINE',				'TXT_KEY_GREAT_WORK_CL_ABC_LATELINE_QUOTE',					'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_MINISTRY_OF_LABOR',			'TXT_KEY_GREAT_WORK_CL_MINISTRY_OF_LABOR',			'TXT_KEY_GREAT_WORK_CL_MINISTRY_OF_LABOR_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_CONCESSION_SPEECH',			'TXT_KEY_GREAT_WORK_CL_CONCESSION_SPEECH',			'TXT_KEY_GREAT_WORK_CL_CONCESSION_SPEECH_QUOTE',			'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_UPON_LEAVING_LABOR_PARTY',	'TXT_KEY_GREAT_WORK_CL_UPON_LEAVING_LABOR_PARTY',	'TXT_KEY_GREAT_WORK_CL_UPON_LEAVING_LABOR_PARTY_QUOTE',		'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_REFERENDUM',					'TXT_KEY_GREAT_WORK_CL_REFERENDUM',					'TXT_KEY_GREAT_WORK_CL_REFERENDUM_QUOTE',					'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_SMH_2012',					'TXT_KEY_GREAT_WORK_CL_SMH_2012',					'TXT_KEY_GREAT_WORK_CL_SMH_2012_QUOTE',						'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK'),
					   ('GREAT_WORK_CL_INTERVIEW_WITH_MARK_RILEY',	'TXT_KEY_GREAT_WORK_CL_INTERVIEW_WITH_MARK_RILEY',	'TXT_KEY_GREAT_WORK_CL_INTERVIEW_WITH_MARK_RILEY_QUOTE',	'GREAT_WORK_LITERATURE',	'GreatWriter_Background.dds',	'AS2D_GREAT_ARTIST_ARTWORK');